"""
Module 3: Compliance & Reporting Automation — Supabase backend
POST /reports/generate              — generate EU ETS / FuelEU / ISO9001 report
GET  /reports/{type}/latest         — fetch latest report of a given type
GET  /reports/{id}/download         — download PDF
POST /compliance/fuel-data          — ingest fuel consumption records
GET  /compliance/fuel-data          — list fuel records
"""
from __future__ import annotations

import json
import uuid
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Optional

import structlog
from fastapi import APIRouter, HTTPException, Query, Request
from fastapi.responses import FileResponse
from pydantic import BaseModel

from middleware.rate_limiter import ai_limit, sync_limit, default_limit
from services.ai_service import parse_compliance_data
from services.report_service import generate_ets_report_pdf, generate_fueleu_report_pdf
from supabase_client import db

log = structlog.get_logger(__name__)
router = APIRouter(prefix="/reports", tags=["compliance"])

REPORT_DIR = Path("/tmp/minoan_reports")
REPORT_DIR.mkdir(parents=True, exist_ok=True)

VALID_REPORT_TYPES = {"eu_ets", "fueleu", "iso9001", "athex_quarterly"}

EMISSION_FACTORS = {"HFO": 3.206, "MGO": 3.206, "LNG": 2.750, "BIOFUEL": 1.5}

# ─── Schemas ─────────────────────────────────────────────────────────────────

class ReportGenerateRequest(BaseModel):
    report_type: str
    report_period: str
    vessel_name: Optional[str] = None
    raw_data: Optional[str] = None
    structured_data: Optional[dict] = None


class FuelDataIngest(BaseModel):
    vessel_name: str
    voyage_id: str
    departure_port: str
    arrival_port: str
    departure_time: datetime
    arrival_time: datetime
    distance_nm: float
    fuel_type: str = "HFO"
    fuel_consumed_mt: float
    is_eu_ets_voyage: bool = True
    idempotency_key: Optional[str] = None


# ─── Endpoints ───────────────────────────────────────────────────────────────

@router.post("/generate")
@ai_limit
async def generate_report(request: Request, payload: ReportGenerateRequest):
    """
    Generate a compliance report. Supports:
    - eu_ets: EU Emissions Trading System allowances calculation
    - fueleu: FuelEU Maritime GHG intensity (mandatory from Jan 2025)
    - iso9001: Quality management audit report
    - athex_quarterly: Athens Stock Exchange quarterly data

    If raw_data is provided, Claude parses and maps it to the schema.
    If structured_data is provided, it's used directly.
    """
    if payload.report_type not in VALID_REPORT_TYPES:
        raise HTTPException(
            status_code=400,
            detail=f"Invalid report_type. Must be one of: {VALID_REPORT_TYPES}",
        )

    log.info("compliance.generate_report", type=payload.report_type, period=payload.report_period)

    # Step 1: Get structured data (AI parse, direct, or DB aggregate)
    if payload.structured_data:
        report_data = payload.structured_data
    elif payload.raw_data:
        report_data = await parse_compliance_data(payload.raw_data, payload.report_type)
    else:
        report_data = _aggregate_fuel_data_from_supabase(
            payload.vessel_name, payload.report_period
        )

    report_data.setdefault("reporting_period", payload.report_period)
    report_data.setdefault("vessel_name", payload.vessel_name or "Fleet-wide")
    report_data.setdefault(
        "disclaimer",
        "Generated by IntegraMind AI for Minoan Lines S.A. — verify against official regulatory filings.",
    )

    # Step 2: Generate PDF
    pdf_bytes = None
    pdf_path = None

    if payload.report_type == "eu_ets":
        pdf_bytes = generate_ets_report_pdf(report_data)
    elif payload.report_type == "fueleu":
        pdf_bytes = generate_fueleu_report_pdf(report_data)

    if pdf_bytes:
        filename = f"{payload.report_type}_{payload.report_period}_{uuid.uuid4().hex[:8]}.pdf"
        pdf_path = str(REPORT_DIR / filename)
        with open(pdf_path, "wb") as f:
            f.write(pdf_bytes)
        log.info("compliance.pdf_generated", path=pdf_path)

    # Step 3: Persist to Supabase
    record = {
        "id": str(uuid.uuid4()),
        "report_type": payload.report_type,
        "report_period": payload.report_period,
        "vessel_name": payload.vessel_name,
        "fuel_consumed_mt": report_data.get("fuel_consumed_mt"),
        "co2_emissions_mt": report_data.get("co2_emissions_mt"),
        "ets_allowances_required": report_data.get("ets_allowances_required"),
        "ets_cost_eur": report_data.get("estimated_ets_cost_eur"),
        "ghg_intensity_gco2eq_mj": report_data.get("ghg_intensity_gco2eq_mj"),
        "fueleu_compliance_balance": report_data.get("compliance_balance_mj"),
        "pdf_path": pdf_path,
        "json_data": json.dumps(report_data),
        "status": "generated",
    }

    res = db().table("compliance_reports").insert(record).execute()
    saved = res.data[0] if res.data else record

    return {
        "id": saved["id"],
        "report_type": saved["report_type"],
        "report_period": saved["report_period"],
        "vessel_name": saved.get("vessel_name"),
        "status": saved.get("status", "generated"),
        "pdf_path": saved.get("pdf_path"),
        "co2_emissions_mt": saved.get("co2_emissions_mt"),
        "ets_cost_eur": saved.get("ets_cost_eur"),
        "created_at": saved.get("created_at", datetime.now(timezone.utc).isoformat()),
    }


@router.get("/{report_type}/latest")
@default_limit
async def get_latest_report(
    request: Request,
    report_type: str,
    vessel_name: Optional[str] = Query(None),
):
    """Fetch the most recently generated report of a given type."""
    if report_type not in VALID_REPORT_TYPES:
        raise HTTPException(status_code=400, detail=f"Invalid report_type: {report_type}")

    query = (
        db().table("compliance_reports")
        .select("*")
        .eq("report_type", report_type)
        .order("created_at", desc=True)
        .limit(1)
    )
    if vessel_name:
        query = query.eq("vessel_name", vessel_name)

    res = query.execute()
    if not res.data:
        raise HTTPException(status_code=404, detail=f"No {report_type} report found")

    r = res.data[0]
    return {
        "id": r["id"],
        "report_type": r["report_type"],
        "report_period": r["report_period"],
        "vessel_name": r.get("vessel_name"),
        "status": r.get("status", "generated"),
        "pdf_path": r.get("pdf_path"),
        "co2_emissions_mt": r.get("co2_emissions_mt"),
        "ets_cost_eur": r.get("ets_cost_eur"),
        "created_at": r.get("created_at"),
    }


@router.get("/{report_id}/download")
@default_limit
async def download_report(request: Request, report_id: str):
    """Download the PDF for a specific report."""
    res = db().table("compliance_reports").select("pdf_path").eq("id", report_id).execute()
    if not res.data:
        raise HTTPException(status_code=404, detail="Report not found")

    pdf_path = res.data[0].get("pdf_path")
    if not pdf_path or not Path(pdf_path).exists():
        raise HTTPException(status_code=404, detail="PDF file not found")

    return FileResponse(
        pdf_path,
        media_type="application/pdf",
        filename=Path(pdf_path).name,
    )


# ─── Fuel data ingestion ──────────────────────────────────────────────────────

fuel_router = APIRouter(prefix="/compliance", tags=["compliance"])


@fuel_router.post("/fuel-data", status_code=201)
@sync_limit
async def ingest_fuel_data(request: Request, payload: FuelDataIngest):
    """Ingest a fuel consumption record from vessel SCADA. Idempotent."""
    idempotency_key = payload.idempotency_key or f"{payload.vessel_name}_{payload.voyage_id}"

    # Idempotency check
    existing = (
        db().table("fuel_consumption_records")
        .select("id")
        .eq("idempotency_key", idempotency_key)
        .execute()
    )
    if existing.data:
        return {"message": "Record already exists (idempotent)", "idempotency_key": idempotency_key}

    factor = EMISSION_FACTORS.get(payload.fuel_type.upper(), 3.206)
    co2 = payload.fuel_consumed_mt * factor

    record = {
        "id": str(uuid.uuid4()),
        "vessel_name": payload.vessel_name,
        "voyage_id": payload.voyage_id,
        "departure_port": payload.departure_port,
        "arrival_port": payload.arrival_port,
        "departure_time": payload.departure_time.isoformat(),
        "arrival_time": payload.arrival_time.isoformat(),
        "distance_nm": payload.distance_nm,
        "fuel_type": payload.fuel_type,
        "fuel_consumed_mt": payload.fuel_consumed_mt,
        "co2_emission_factor": factor,
        "co2_emissions_mt": co2,
        "is_eu_ets_voyage": payload.is_eu_ets_voyage,
        "idempotency_key": idempotency_key,
    }

    db().table("fuel_consumption_records").insert(record).execute()
    log.info("compliance.fuel_ingested", vessel=payload.vessel_name, voyage=payload.voyage_id, co2=co2)

    return {"message": "Fuel record ingested", "voyage_id": payload.voyage_id, "co2_mt": co2}


@fuel_router.get("/fuel-data")
@default_limit
async def list_fuel_data(
    request: Request,
    vessel_name: Optional[str] = Query(None),
    limit: int = Query(50, ge=1, le=200),
    offset: int = Query(0, ge=0),
):
    """List fuel consumption records with optional vessel filter."""
    query = (
        db().table("fuel_consumption_records")
        .select("*")
        .order("departure_time", desc=True)
        .range(offset, offset + limit - 1)
    )
    if vessel_name:
        query = query.eq("vessel_name", vessel_name)

    res = query.execute()
    return res.data or []


# ─── Helpers ─────────────────────────────────────────────────────────────────

def _aggregate_fuel_data_from_supabase(
    vessel_name: Optional[str],
    period: str,
) -> dict[str, Any]:
    """Aggregate fuel records from Supabase for the reporting period."""
    try:
        query = db().table("fuel_consumption_records").select("fuel_consumed_mt,co2_emissions_mt,is_eu_ets_voyage")
        if vessel_name:
            query = query.eq("vessel_name", vessel_name)
        res = query.execute()
        records = res.data or []

        total_fuel = sum(r.get("fuel_consumed_mt") or 0 for r in records)
        total_co2 = sum(r.get("co2_emissions_mt") or 0 for r in records)
        ets_coverage = 1.0

        return {
            "fuel_type": "HFO",
            "fuel_consumed_mt": total_fuel,
            "co2_emission_factor": 3.206,
            "co2_emissions_mt": total_co2,
            "voyage_type": "intra_eu",
            "ets_coverage_pct": int(ets_coverage * 100),
            "ets_allowances_required": total_co2 * ets_coverage,
            "ets_price_per_tonne_eur": 65.0,
            "estimated_ets_cost_eur": total_co2 * ets_coverage * 65.0,
        }
    except Exception as exc:
        log.error("compliance.aggregate_error", error=str(exc))
        return {
            "fuel_type": "HFO",
            "fuel_consumed_mt": 0.0,
            "co2_emissions_mt": 0.0,
            "ets_allowances_required": 0.0,
            "estimated_ets_cost_eur": 0.0,
        }