"""
PDF report generation service for Module 3.
Uses ReportLab for PDF creation.
"""
from __future__ import annotations

import io
from datetime import datetime
from typing import Any

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm
from reportlab.platypus import (
    HRFlowable, Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle,
)

DISCLAIMER = (
    "Generated by IntegraMind AI for Minoan Lines S.A. — "
    "verify against official regulatory filings."
)

MINOAN_BLUE = colors.HexColor("#003087")
MINOAN_GOLD = colors.HexColor("#C9A84C")


def generate_ets_report_pdf(report_data: dict[str, Any]) -> bytes:
    """Generate EU ETS compliance report PDF. Returns raw bytes."""
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        rightMargin=2 * cm,
        leftMargin=2 * cm,
        topMargin=2.5 * cm,
        bottomMargin=2 * cm,
    )
    styles = getSampleStyleSheet()
    story = []

    # Header
    story.append(_header_paragraph("EU Emissions Trading System (ETS) Report", styles))
    story.append(_sub_header("Minoan Lines S.A. | Heraklion, Crete", styles))
    story.append(Spacer(1, 0.5 * cm))
    story.append(HRFlowable(width="100%", thickness=2, color=MINOAN_BLUE))
    story.append(Spacer(1, 0.3 * cm))

    # Metadata
    meta_data = [
        ["Report Period:", report_data.get("reporting_period", "N/A")],
        ["Vessel:", report_data.get("vessel_name", "Fleet-wide")],
        ["Generated:", datetime.now().strftime("%d %B %Y %H:%M UTC")],
        ["Reporting Entity:", "Minoan Lines S.A."],
        ["Parent Group:", "Grimaldi Group (95.9% ownership)"],
    ]
    story.append(_two_col_table(meta_data, styles))
    story.append(Spacer(1, 0.5 * cm))

    # Emissions summary
    story.append(_section_header("Emissions Summary", styles))
    emissions_data = [
        ["Parameter", "Value", "Unit"],
        ["Fuel Type", report_data.get("fuel_type", "HFO"), ""],
        ["Fuel Consumed", f"{report_data.get('fuel_consumed_mt', 0):.2f}", "metric tonnes"],
        ["CO₂ Emission Factor", f"{report_data.get('co2_emission_factor', 3.206):.3f}", "tCO₂/tFuel"],
        ["CO₂ Emissions", f"{report_data.get('co2_emissions_mt', 0):.2f}", "metric tonnes CO₂"],
        ["ETS Coverage", f"{report_data.get('ets_coverage_pct', 100)}%", "of voyage"],
        ["ETS Allowances Required", f"{report_data.get('ets_allowances_required', 0):.2f}", "EUAs"],
        ["ETS Carbon Price", f"€{report_data.get('ets_price_per_tonne_eur', 65):.2f}", "per tonne"],
        ["Estimated ETS Cost", f"€{report_data.get('estimated_ets_cost_eur', 0):.2f}", "EUR"],
    ]
    story.append(_data_table(emissions_data, styles))
    story.append(Spacer(1, 0.5 * cm))

    # Voyage details
    story.append(_section_header("Voyage Classification", styles))
    voyage_data = [
        ["Voyage Type:", report_data.get("voyage_type", "intra_eu").replace("_", " → ").title()],
        ["Departure Port:", report_data.get("departure_port", "N/A")],
        ["Arrival Port:", report_data.get("arrival_port", "N/A")],
        ["Voyage ID:", report_data.get("voyage_id", "N/A")],
    ]
    story.append(_two_col_table(voyage_data, styles))
    story.append(Spacer(1, 1 * cm))

    # Disclaimer
    story.append(HRFlowable(width="100%", thickness=1, color=MINOAN_GOLD))
    story.append(Spacer(1, 0.2 * cm))
    disclaimer_style = ParagraphStyle(
        "disclaimer",
        parent=styles["Normal"],
        fontSize=8,
        textColor=colors.grey,
        italic=True,
    )
    story.append(Paragraph(DISCLAIMER, disclaimer_style))

    doc.build(story)
    return buffer.getvalue()


def generate_fueleu_report_pdf(report_data: dict[str, Any]) -> bytes:
    """Generate FuelEU Maritime compliance report PDF."""
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4, rightMargin=2*cm, leftMargin=2*cm,
                            topMargin=2.5*cm, bottomMargin=2*cm)
    styles = getSampleStyleSheet()
    story = []

    story.append(_header_paragraph("FuelEU Maritime GHG Intensity Report", styles))
    story.append(_sub_header("Minoan Lines S.A. | Regulation (EU) 2023/1805", styles))
    story.append(Spacer(1, 0.5*cm))
    story.append(HRFlowable(width="100%", thickness=2, color=MINOAN_BLUE))
    story.append(Spacer(1, 0.3*cm))

    story.append(_section_header("GHG Intensity Assessment", styles))
    fueleu_data = [
        ["Parameter", "Value", "Unit"],
        ["Reporting Period", report_data.get("reporting_period", "N/A"), ""],
        ["Vessel", report_data.get("vessel_name", "N/A"), ""],
        ["Energy Used", f"{report_data.get('energy_used_mj', 0):.0f}", "MJ"],
        ["GHG Emissions", f"{report_data.get('ghg_emissions_gco2eq', 0):.0f}", "gCO₂eq"],
        ["GHG Intensity (actual)", f"{report_data.get('ghg_intensity_gco2eq_mj', 0):.2f}", "gCO₂eq/MJ"],
        ["2025 Regulatory Limit", "91.16", "gCO₂eq/MJ"],
        ["Compliance Balance", f"{report_data.get('compliance_balance_mj', 0):.0f}", "MJ"],
        ["Status", report_data.get("surplus_or_deficit", "N/A").upper(), ""],
        ["Penalty (if deficit)", f"€{report_data.get('penalty_eur', 0):.2f}", "EUR"],
    ]
    story.append(_data_table(fueleu_data, styles))
    story.append(Spacer(1, 1*cm))
    story.append(HRFlowable(width="100%", thickness=1, color=MINOAN_GOLD))
    story.append(Spacer(1, 0.2*cm))
    disclaimer_style = ParagraphStyle("disclaimer", parent=styles["Normal"],
                                      fontSize=8, textColor=colors.grey, italic=True)
    story.append(Paragraph(DISCLAIMER, disclaimer_style))
    doc.build(story)
    return buffer.getvalue()


# ─── ReportLab helpers ────────────────────────────────────────────────────────

def _header_paragraph(text: str, styles) -> Paragraph:
    style = ParagraphStyle("title", parent=styles["Title"],
                           textColor=MINOAN_BLUE, fontSize=16, spaceAfter=4)
    return Paragraph(text, style)


def _sub_header(text: str, styles) -> Paragraph:
    style = ParagraphStyle("subtitle", parent=styles["Normal"],
                           textColor=MINOAN_GOLD, fontSize=10, spaceAfter=2)
    return Paragraph(text, style)


def _section_header(text: str, styles) -> Paragraph:
    style = ParagraphStyle("section", parent=styles["Heading2"],
                           textColor=MINOAN_BLUE, fontSize=12, spaceBefore=8, spaceAfter=4)
    return Paragraph(text, style)


def _two_col_table(data: list[list], styles) -> Table:
    table = Table(data, colWidths=[5*cm, 12*cm])
    table.setStyle(TableStyle([
        ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
        ("FONTNAME", (1, 0), (1, -1), "Helvetica"),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("TEXTCOLOR", (0, 0), (0, -1), MINOAN_BLUE),
        ("ROWBACKGROUNDS", (0, 0), (-1, -1), [colors.whitesmoke, colors.white]),
        ("GRID", (0, 0), (-1, -1), 0.25, colors.lightgrey),
        ("TOPPADDING", (0, 0), (-1, -1), 3),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
    ]))
    return table


def _data_table(data: list[list], styles) -> Table:
    table = Table(data, colWidths=[8*cm, 5*cm, 4*cm])
    header_bg = MINOAN_BLUE
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), header_bg),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.whitesmoke, colors.white]),
        ("GRID", (0, 0), (-1, -1), 0.25, colors.lightgrey),
        ("ALIGN", (1, 1), (-1, -1), "RIGHT"),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
    ]))
    return table
