'use client';
import i18n from 'i18next';
import { initReactI18next } from 'react-i18next';
import LanguageDetector from 'i18next-browser-languagedetector';

export const LANGUAGES: Record<string, string> = {
  en: 'English',
  el: 'Ελληνικά',
  es: 'Español',
  fr: 'Français',
  de: 'Deutsch',
  it: 'Italiano',
  pt: 'Português',
  ar: 'العربية',
  zh: '中文',
  ja: '日本語',
  ru: 'Русский',
  tr: 'Türkçe',
  nl: 'Nederlands',
  pl: 'Polski',
  sv: 'Svenska',
  ko: '한국어',
  hi: 'हिन्दी',
  uk: 'Українська',
  ro: 'Română',
  cs: 'Čeština',
};

const resources = {
  en: {
    translation: {
      nav: { vessels: 'Vessel Ops', chat: 'AI Agent', compliance: 'Compliance', helpdesk: 'Helpdesk', analytics: 'Analytics' },
      home: { title: 'Minoan Lines AI Platform', subtitle: 'AI-Powered Operations Platform — Powered by IntegraMind AI × DeepSeek' },
      vessels: { title: 'Vessel Operations', refresh: 'Refresh', lastUpdated: 'Last updated', speed: 'Speed', fuel: 'Fuel', eta: 'ETA', delayRisk: 'Delay Risk', status: { underway: 'Underway', at_anchor: 'At Anchor', moored: 'Moored' } },
      chat: { title: 'AI Customer Agent', placeholder: 'Type your message...', suggestions: ['What routes does Minoan Lines operate?', 'When is the next departure to Heraklion?', 'What cabin options are available?', 'How early should I arrive at the port?'] },
      compliance: { title: 'EU Compliance', refresh: 'Refresh', generateReport: 'Generate Report', generating: 'Generating...', totalCO2: 'Total CO₂ (tons)', etsAllowances: 'ETS Allowances', avgCII: 'Avg CII Score', reportDate: 'Report Date', euEts: 'EU ETS Report', fuelEu: 'FuelEU Maritime' },
      helpdesk: { title: 'IT Helpdesk', newTicket: 'New Ticket', submit: 'Submit (AI will triage)', titleLabel: 'Issue title', descLabel: 'Describe the issue', nameLabel: 'Your name (optional)', noTickets: 'No tickets found. Create one to get started!', markInProgress: 'Mark In Progress', markResolved: 'Mark Resolved', escalate: 'Escalate', aiSuggested: 'AI Suggested Response', bookingRef: 'Booking Ref', ticketNumber: 'Ticket No.', filters: { all: 'All', open: 'Open', in_progress: 'In Progress', resolved: 'Resolved', escalated: 'Escalated' } },
      analytics: { title: 'Demand Analytics', refresh: 'Refresh', weeklyPassengers: 'Weekly Passengers', weeklyRevenue: 'Weekly Revenue', peakRoute: 'Peak Route', forecastAccuracy: 'Forecast Accuracy', generateInsights: 'Generate Insights for', forecastTitle: '7-Day Demand Forecast', aiInsights: 'AI Demand Insights' },
      common: { loading: 'Loading...', error: 'An error occurred', retry: 'Retry' },
    },
  },
  el: {
    translation: {
      nav: { vessels: 'Πλοία', chat: 'AI Πράκτορας', compliance: 'Συμμόρφωση', helpdesk: 'Helpdesk', analytics: 'Αναλυτικά' },
      home: { title: 'Πλατφόρμα AI Minoan Lines', subtitle: 'Πλατφόρμα Λειτουργιών AI — Powered by IntegraMind AI × DeepSeek' },
      vessels: { title: 'Επιχειρήσεις Πλοίων', refresh: 'Ανανέωση', lastUpdated: 'Τελευταία ενημέρωση', speed: 'Ταχύτητα', fuel: 'Καύσιμα', eta: 'Εκτ. Άφιξη', delayRisk: 'Κίνδυνος Καθυστέρησης', status: { underway: 'Εν πλω', at_anchor: 'Αγκυροβολημένο', moored: 'Δεμένο' } },
      chat: { title: 'AI Εξυπηρέτηση Πελατών', placeholder: 'Γράψτε το μήνυμά σας...', suggestions: ['Ποιες διαδρομές εξυπηρετεί η Minoan Lines;', 'Πότε είναι η επόμενη αναχώρηση για Ηράκλειο;', 'Ποιες επιλογές καμπίνας υπάρχουν;', 'Πότε πρέπει να φτάσω στο λιμάνι;'] },
      compliance: { title: 'ΕΕ Συμμόρφωση', refresh: 'Ανανέωση', generateReport: 'Δημιουργία Αναφοράς', generating: 'Δημιουργία...', totalCO2: 'Συνολικό CO₂ (τόνοι)', etsAllowances: 'Δικαιώματα ETS', avgCII: 'Μέσο CII', reportDate: 'Ημερομηνία Αναφοράς', euEts: 'Αναφορά EU ETS', fuelEu: 'FuelEU Maritime' },
      helpdesk: { title: 'Helpdesk Πληροφορικής', newTicket: 'Νέο Εισιτήριο', submit: 'Υποβολή (AI θα αναλύσει)', titleLabel: 'Τίτλος προβλήματος', descLabel: 'Περιγράψτε το πρόβλημα', nameLabel: 'Όνομά σας (προαιρετικό)', noTickets: 'Δεν βρέθηκαν εισιτήρια. Δημιουργήστε ένα!', markInProgress: 'Σε εξέλιξη', markResolved: 'Επίλυση', escalate: 'Κλιμάκωση', aiSuggested: 'AI Προτεινόμενη Απάντηση', bookingRef: 'Αριθ. Κράτησης', ticketNumber: 'Αριθ. Εισιτηρίου', filters: { all: 'Όλα', open: 'Ανοιχτά', in_progress: 'Σε εξέλιξη', resolved: 'Επιλυμένα', escalated: 'Κλιμακωμένα' } },
      analytics: { title: 'Αναλυτικά Ζήτησης', refresh: 'Ανανέωση', weeklyPassengers: 'Εβδομαδιαίοι Επιβάτες', weeklyRevenue: 'Εβδομαδιαία Έσοδα', peakRoute: 'Κορυφαία Διαδρομή', forecastAccuracy: 'Ακρίβεια Πρόβλεψης', generateInsights: 'Δημιουργία Insights για', forecastTitle: 'Πρόβλεψη 7 Ημερών', aiInsights: 'AI Insights Ζήτησης' },
      common: { loading: 'Φόρτωση...', error: 'Παρουσιάστηκε σφάλμα', retry: 'Επανάληψη' },
    },
  },
  es: {
    translation: {
      nav: { vessels: 'Operaciones', chat: 'Agente AI', compliance: 'Cumplimiento', helpdesk: 'Soporte', analytics: 'Analítica' },
      home: { title: 'Plataforma AI de Minoan Lines', subtitle: 'Plataforma de Operaciones AI — Powered by IntegraMind AI × DeepSeek' },
      vessels: { title: 'Operaciones de Buques', refresh: 'Actualizar', lastUpdated: 'Última actualización', speed: 'Velocidad', fuel: 'Combustible', eta: 'ETA', delayRisk: 'Riesgo de Retraso', status: { underway: 'En marcha', at_anchor: 'Anclado', moored: 'Atracado' } },
      chat: { title: 'Agente AI de Atención al Cliente', placeholder: 'Escribe tu mensaje...', suggestions: ['¿Qué rutas opera Minoan Lines?', '¿Cuándo es la próxima salida a Heraklion?', '¿Qué opciones de camarote hay?', '¿Cuándo debo llegar al puerto?'] },
      compliance: { title: 'Cumplimiento UE', refresh: 'Actualizar', generateReport: 'Generar Informe', generating: 'Generando...', totalCO2: 'CO₂ Total (tons)', etsAllowances: 'Permisos ETS', avgCII: 'CII Promedio', reportDate: 'Fecha Informe', euEts: 'Informe EU ETS', fuelEu: 'FuelEU Maritime' },
      helpdesk: { title: 'Soporte IT', newTicket: 'Nuevo Ticket', submit: 'Enviar (AI clasificará)', titleLabel: 'Título del problema', descLabel: 'Describe el problema', nameLabel: 'Tu nombre (opcional)', noTickets: '¡No hay tickets. Crea uno!', markInProgress: 'En Progreso', markResolved: 'Resolver', escalate: 'Escalar', aiSuggested: 'Respuesta Sugerida AI', bookingRef: 'Ref. Reserva', ticketNumber: 'Núm. Ticket', filters: { all: 'Todos', open: 'Abiertos', in_progress: 'En Progreso', resolved: 'Resueltos', escalated: 'Escalados' } },
      analytics: { title: 'Analítica de Demanda', refresh: 'Actualizar', weeklyPassengers: 'Pasajeros Semanales', weeklyRevenue: 'Ingresos Semanales', peakRoute: 'Ruta Principal', forecastAccuracy: 'Precisión Pronóstico', generateInsights: 'Generar Insights para', forecastTitle: 'Pronóstico 7 Días', aiInsights: 'Insights AI de Demanda' },
      common: { loading: 'Cargando...', error: 'Ocurrió un error', retry: 'Reintentar' },
    },
  },
  fr: {
    translation: {
      nav: { vessels: 'Opérations', chat: 'Agent AI', compliance: 'Conformité', helpdesk: 'Support', analytics: 'Analytique' },
      home: { title: 'Plateforme AI Minoan Lines', subtitle: 'Plateforme d\'Opérations AI — Powered by IntegraMind AI × DeepSeek' },
      vessels: { title: 'Opérations Navires', refresh: 'Actualiser', lastUpdated: 'Dernière mise à jour', speed: 'Vitesse', fuel: 'Carburant', eta: 'ETA', delayRisk: 'Risque Retard', status: { underway: 'En route', at_anchor: 'À l\'ancre', moored: 'Amarré' } },
      chat: { title: 'Agent AI Client', placeholder: 'Écrivez votre message...', suggestions: ['Quelles routes Minoan Lines opère-t-elle?', 'Quand est le prochain départ pour Héraklion?', 'Quelles options de cabine sont disponibles?', 'Quand arriver au port?'] },
      compliance: { title: 'Conformité UE', refresh: 'Actualiser', generateReport: 'Générer Rapport', generating: 'Génération...', totalCO2: 'CO₂ Total (tonnes)', etsAllowances: 'Quotas ETS', avgCII: 'CII Moyen', reportDate: 'Date Rapport', euEts: 'Rapport EU ETS', fuelEu: 'FuelEU Maritime' },
      helpdesk: { title: 'Support IT', newTicket: 'Nouveau Ticket', submit: 'Soumettre (AI triera)', titleLabel: 'Titre du problème', descLabel: 'Décrivez le problème', nameLabel: 'Votre nom (optionnel)', noTickets: 'Pas de tickets. Créez-en un!', markInProgress: 'En cours', markResolved: 'Résolu', escalate: 'Escalader', aiSuggested: 'Réponse Suggérée AI', bookingRef: 'Réf. Réservation', ticketNumber: 'No. Ticket', filters: { all: 'Tous', open: 'Ouverts', in_progress: 'En cours', resolved: 'Résolus', escalated: 'Escaladés' } },
      analytics: { title: 'Analytique de Demande', refresh: 'Actualiser', weeklyPassengers: 'Passagers Hebdo', weeklyRevenue: 'Revenus Hebdo', peakRoute: 'Route Principale', forecastAccuracy: 'Précision Prévision', generateInsights: 'Générer Insights pour', forecastTitle: 'Prévision 7 Jours', aiInsights: 'Insights AI Demande' },
      common: { loading: 'Chargement...', error: 'Une erreur s\'est produite', retry: 'Réessayer' },
    },
  },
  de: {
    translation: {
      nav: { vessels: 'Schiffsbetrieb', chat: 'KI-Agent', compliance: 'Compliance', helpdesk: 'Support', analytics: 'Analytik' },
      home: { title: 'Minoan Lines KI-Plattform', subtitle: 'KI-Betriebsplattform — Powered by IntegraMind AI × DeepSeek' },
      vessels: { title: 'Schiffsbetrieb', refresh: 'Aktualisieren', lastUpdated: 'Zuletzt aktualisiert', speed: 'Geschwindigkeit', fuel: 'Kraftstoff', eta: 'ETA', delayRisk: 'Verzögerungsrisiko', status: { underway: 'Unterwegs', at_anchor: 'Vor Anker', moored: 'Festgemacht' } },
      chat: { title: 'KI-Kundenservice', placeholder: 'Ihre Nachricht eingeben...', suggestions: ['Welche Routen betreibt Minoan Lines?', 'Wann ist die nächste Abfahrt nach Heraklion?', 'Welche Kabinenoptionen gibt es?', 'Wann sollte ich am Hafen ankommen?'] },
      compliance: { title: 'EU-Compliance', refresh: 'Aktualisieren', generateReport: 'Bericht erstellen', generating: 'Wird erstellt...', totalCO2: 'Gesamt-CO₂ (Tonnen)', etsAllowances: 'ETS-Zertifikate', avgCII: 'Durchschn. CII', reportDate: 'Berichtsdatum', euEts: 'EU-ETS-Bericht', fuelEu: 'FuelEU Maritime' },
      helpdesk: { title: 'IT-Helpdesk', newTicket: 'Neues Ticket', submit: 'Absenden (KI priorisiert)', titleLabel: 'Problem-Titel', descLabel: 'Problem beschreiben', nameLabel: 'Ihr Name (optional)', noTickets: 'Keine Tickets. Erstellen Sie eines!', markInProgress: 'In Bearbeitung', markResolved: 'Gelöst', escalate: 'Eskalieren', aiSuggested: 'KI-Vorgeschlagene Antwort', bookingRef: 'Buchungsref.', ticketNumber: 'Ticket-Nr.', filters: { all: 'Alle', open: 'Offen', in_progress: 'In Bearbeitung', resolved: 'Gelöst', escalated: 'Eskaliert' } },
      analytics: { title: 'Nachfrageanalyse', refresh: 'Aktualisieren', weeklyPassengers: 'Wöchentliche Passagiere', weeklyRevenue: 'Wöchentlicher Umsatz', peakRoute: 'Hauptroute', forecastAccuracy: 'Prognosegenauigkeit', generateInsights: 'Insights generieren für', forecastTitle: '7-Tage-Prognose', aiInsights: 'KI-Nachfrage-Insights' },
      common: { loading: 'Wird geladen...', error: 'Ein Fehler ist aufgetreten', retry: 'Wiederholen' },
    },
  },
  it: {
    translation: {
      nav: { vessels: 'Operazioni', chat: 'Agente AI', compliance: 'Conformità', helpdesk: 'Supporto', analytics: 'Analisi' },
      home: { title: 'Piattaforma AI Minoan Lines', subtitle: 'Piattaforma Operativa AI — Powered by IntegraMind AI × DeepSeek' },
      vessels: { title: 'Operazioni Navali', refresh: 'Aggiorna', lastUpdated: 'Ultimo aggiornamento', speed: 'Velocità', fuel: 'Carburante', eta: 'ETA', delayRisk: 'Rischio Ritardo', status: { underway: 'In navigazione', at_anchor: 'All\'ancora', moored: 'Ormeggiato' } },
      chat: { title: 'Agente AI Clienti', placeholder: 'Scrivi il tuo messaggio...', suggestions: ['Quali rotte opera Minoan Lines?', 'Quando è la prossima partenza per Heraklion?', 'Quali cabine sono disponibili?', 'Quando arrivare al porto?'] },
      compliance: { title: 'Conformità UE', refresh: 'Aggiorna', generateReport: 'Genera Rapporto', generating: 'Generazione...', totalCO2: 'CO₂ Totale (ton)', etsAllowances: 'Quote ETS', avgCII: 'CII Medio', reportDate: 'Data Rapporto', euEts: 'Rapporto EU ETS', fuelEu: 'FuelEU Maritime' },
      helpdesk: { title: 'Helpdesk IT', newTicket: 'Nuovo Ticket', submit: 'Invia (AI classificherà)', titleLabel: 'Titolo problema', descLabel: 'Descrivi il problema', nameLabel: 'Il tuo nome (opzionale)', noTickets: 'Nessun ticket. Creane uno!', markInProgress: 'In Lavorazione', markResolved: 'Risolto', escalate: 'Escalation', aiSuggested: 'Risposta Suggerita AI', bookingRef: 'Rif. Prenotazione', ticketNumber: 'N. Ticket', filters: { all: 'Tutti', open: 'Aperti', in_progress: 'In corso', resolved: 'Risolti', escalated: 'Escalati' } },
      analytics: { title: 'Analisi della Domanda', refresh: 'Aggiorna', weeklyPassengers: 'Passeggeri Settimanali', weeklyRevenue: 'Ricavi Settimanali', peakRoute: 'Rotta Principale', forecastAccuracy: 'Accuratezza Previsione', generateInsights: 'Genera Insights per', forecastTitle: 'Previsione 7 Giorni', aiInsights: 'AI Insights Domanda' },
      common: { loading: 'Caricamento...', error: 'Si è verificato un errore', retry: 'Riprova' },
    },
  },
  pt: {
    translation: {
      nav: { vessels: 'Operações', chat: 'Agente AI', compliance: 'Conformidade', helpdesk: 'Suporte', analytics: 'Análise' },
      home: { title: 'Plataforma AI Minoan Lines', subtitle: 'Plataforma de Operações AI — Powered by IntegraMind AI × DeepSeek' },
      vessels: { title: 'Operações de Navios', refresh: 'Atualizar', lastUpdated: 'Última atualização', speed: 'Velocidade', fuel: 'Combustível', eta: 'ETA', delayRisk: 'Risco de Atraso', status: { underway: 'Em navegação', at_anchor: 'Ancorado', moored: 'Atracado' } },
      chat: { title: 'Agente AI de Clientes', placeholder: 'Escreva sua mensagem...', suggestions: ['Quais rotas a Minoan Lines opera?', 'Quando é a próxima partida para Heraklion?', 'Que opções de cabine existem?', 'Quando chegar ao porto?'] },
      compliance: { title: 'Conformidade UE', refresh: 'Atualizar', generateReport: 'Gerar Relatório', generating: 'Gerando...', totalCO2: 'CO₂ Total (ton)', etsAllowances: 'Licenças ETS', avgCII: 'CII Médio', reportDate: 'Data Relatório', euEts: 'Relatório EU ETS', fuelEu: 'FuelEU Maritime' },
      helpdesk: { title: 'Helpdesk TI', newTicket: 'Novo Ticket', submit: 'Enviar (AI triará)', titleLabel: 'Título do problema', descLabel: 'Descreva o problema', nameLabel: 'Seu nome (opcional)', noTickets: 'Nenhum ticket. Crie um!', markInProgress: 'Em Andamento', markResolved: 'Resolvido', escalate: 'Escalar', aiSuggested: 'Resposta Sugerida AI', bookingRef: 'Ref. Reserva', ticketNumber: 'Núm. Ticket', filters: { all: 'Todos', open: 'Abertos', in_progress: 'Em andamento', resolved: 'Resolvidos', escalated: 'Escalados' } },
      analytics: { title: 'Análise de Demanda', refresh: 'Atualizar', weeklyPassengers: 'Passageiros Semanais', weeklyRevenue: 'Receita Semanal', peakRoute: 'Rota Principal', forecastAccuracy: 'Precisão da Previsão', generateInsights: 'Gerar Insights para', forecastTitle: 'Previsão de 7 Dias', aiInsights: 'AI Insights de Demanda' },
      common: { loading: 'Carregando...', error: 'Ocorreu um erro', retry: 'Tentar novamente' },
    },
  },
  ar: {
    translation: {
      nav: { vessels: 'عمليات السفن', chat: 'وكيل الذكاء الاصطناعي', compliance: 'الامتثال', helpdesk: 'الدعم', analytics: 'التحليلات' },
      home: { title: 'منصة Minoan Lines الذكية', subtitle: 'منصة عمليات الذكاء الاصطناعي — Powered by IntegraMind AI × DeepSeek' },
      vessels: { title: 'عمليات السفن', refresh: 'تحديث', lastUpdated: 'آخر تحديث', speed: 'السرعة', fuel: 'الوقود', eta: 'وقت الوصول', delayRisk: 'خطر التأخير', status: { underway: 'في الإبحار', at_anchor: 'في المرساة', moored: 'مرسو' } },
      chat: { title: 'وكيل خدمة العملاء AI', placeholder: 'اكتب رسالتك...', suggestions: ['ما الخطوط التي تشغلها Minoan Lines؟', 'متى الرحلة القادمة إلى هيراكليون؟', 'ما خيارات الكابينة المتاحة؟', 'متى يجب أن أصل إلى الميناء؟'] },
      compliance: { title: 'الامتثال الأوروبي', refresh: 'تحديث', generateReport: 'إنشاء تقرير', generating: 'جارٍ الإنشاء...', totalCO2: 'إجمالي CO₂ (طن)', etsAllowances: 'تصاريح ETS', avgCII: 'متوسط CII', reportDate: 'تاريخ التقرير', euEts: 'تقرير EU ETS', fuelEu: 'FuelEU Maritime' },
      helpdesk: { title: 'دعم تقنية المعلومات', newTicket: 'تذكرة جديدة', submit: 'إرسال (سيصنفها الذكاء الاصطناعي)', titleLabel: 'عنوان المشكلة', descLabel: 'وصف المشكلة', nameLabel: 'اسمك (اختياري)', noTickets: 'لا توجد تذاكر. أنشئ واحدة!', markInProgress: 'قيد التنفيذ', markResolved: 'تم الحل', escalate: 'تصعيد', aiSuggested: 'رد مقترح من AI', bookingRef: 'رقم الحجز', ticketNumber: 'رقم التذكرة', filters: { all: 'الكل', open: 'مفتوح', in_progress: 'قيد التنفيذ', resolved: 'محلول', escalated: 'مصعَّد' } },
      analytics: { title: 'تحليلات الطلب', refresh: 'تحديث', weeklyPassengers: 'الركاب الأسبوعيون', weeklyRevenue: 'الإيرادات الأسبوعية', peakRoute: 'أعلى خط', forecastAccuracy: 'دقة التنبؤ', generateInsights: 'إنشاء رؤى لـ', forecastTitle: 'توقعات 7 أيام', aiInsights: 'رؤى AI للطلب' },
      common: { loading: 'جارٍ التحميل...', error: 'حدث خطأ', retry: 'إعادة المحاولة' },
    },
  },
  zh: {
    translation: {
      nav: { vessels: '船舶运营', chat: 'AI客服', compliance: '合规', helpdesk: '帮助台', analytics: '分析' },
      home: { title: 'Minoan Lines AI平台', subtitle: 'AI运营平台 — Powered by IntegraMind AI × DeepSeek' },
      vessels: { title: '船舶运营', refresh: '刷新', lastUpdated: '最后更新', speed: '速度', fuel: '燃油', eta: '预计到达', delayRisk: '延误风险', status: { underway: '航行中', at_anchor: '锚泊', moored: '停靠' } },
      chat: { title: 'AI客户服务', placeholder: '输入您的消息...', suggestions: ['Minoan Lines运营哪些航线？', '下一班前往Heraklion的船何时出发？', '有哪些舱位选择？', '我应该什么时候到达港口？'] },
      compliance: { title: 'EU合规', refresh: '刷新', generateReport: '生成报告', generating: '生成中...', totalCO2: '总CO₂（吨）', etsAllowances: 'ETS配额', avgCII: '平均CII', reportDate: '报告日期', euEts: 'EU ETS报告', fuelEu: 'FuelEU Maritime' },
      helpdesk: { title: 'IT服务台', newTicket: '新建工单', submit: '提交（AI将分类）', titleLabel: '问题标题', descLabel: '描述问题', nameLabel: '您的姓名（可选）', noTickets: '暂无工单，创建一个吧！', markInProgress: '处理中', markResolved: '已解决', escalate: '升级', aiSuggested: 'AI建议回复', bookingRef: '预订参考', ticketNumber: '票号', filters: { all: '全部', open: '待处理', in_progress: '处理中', resolved: '已解决', escalated: '已升级' } },
      analytics: { title: '需求分析', refresh: '刷新', weeklyPassengers: '每周乘客', weeklyRevenue: '每周收入', peakRoute: '主要航线', forecastAccuracy: '预测准确率', generateInsights: '生成洞察：', forecastTitle: '7天需求预测', aiInsights: 'AI需求洞察' },
      common: { loading: '加载中...', error: '发生错误', retry: '重试' },
    },
  },
  ja: {
    translation: {
      nav: { vessels: '船舶運航', chat: 'AIエージェント', compliance: 'コンプライアンス', helpdesk: 'ヘルプデスク', analytics: '分析' },
      home: { title: 'Minoan Lines AIプラットフォーム', subtitle: 'AI運営プラットフォーム — Powered by IntegraMind AI × DeepSeek' },
      vessels: { title: '船舶運航', refresh: '更新', lastUpdated: '最終更新', speed: '速度', fuel: '燃料', eta: 'ETA', delayRisk: '遅延リスク', status: { underway: '航行中', at_anchor: '錨泊中', moored: '係留中' } },
      chat: { title: 'AI顧客サービス', placeholder: 'メッセージを入力...', suggestions: ['Minoan Linesはどのルートを運航していますか？', 'ヘラクリオン行きの次の便はいつですか？', 'どのようなキャビンオプションがありますか？', '港にはいつ到着すればいいですか？'] },
      compliance: { title: 'EUコンプライアンス', refresh: '更新', generateReport: 'レポート生成', generating: '生成中...', totalCO2: '総CO₂（トン）', etsAllowances: 'ETS割当量', avgCII: '平均CII', reportDate: 'レポート日付', euEts: 'EU ETSレポート', fuelEu: 'FuelEU Maritime' },
      helpdesk: { title: 'ITヘルプデスク', newTicket: '新規チケット', submit: '送信（AIが分類）', titleLabel: '問題のタイトル', descLabel: '問題を説明', nameLabel: 'お名前（任意）', noTickets: 'チケットがありません。作成してください！', markInProgress: '対応中', markResolved: '解決済み', escalate: 'エスカレート', aiSuggested: 'AI提案返答', bookingRef: '予約番号', ticketNumber: 'チケット番号', filters: { all: 'すべて', open: '未対応', in_progress: '対応中', resolved: '解決済み', escalated: 'エスカレート済み' } },
      analytics: { title: '需要分析', refresh: '更新', weeklyPassengers: '週間旅客数', weeklyRevenue: '週間収益', peakRoute: 'ピークルート', forecastAccuracy: '予測精度', generateInsights: 'インサイト生成：', forecastTitle: '7日間需要予測', aiInsights: 'AI需要インサイト' },
      common: { loading: '読み込み中...', error: 'エラーが発生しました', retry: '再試行' },
    },
  },
  ru: { translation: { nav: { vessels: 'Суда', chat: 'ИИ-агент', compliance: 'Соответствие', helpdesk: 'Поддержка', analytics: 'Аналитика' }, home: { title: 'ИИ-платформа Minoan Lines', subtitle: 'Операционная ИИ-платформа — Powered by IntegraMind AI × DeepSeek' }, vessels: { title: 'Операции флота', refresh: 'Обновить', lastUpdated: 'Последнее обновление', speed: 'Скорость', fuel: 'Топливо', eta: 'ОВП', delayRisk: 'Риск задержки', status: { underway: 'В пути', at_anchor: 'На якоре', moored: 'Пришвартован' } }, chat: { title: 'ИИ-служба поддержки', placeholder: 'Введите сообщение...', suggestions: ['Какие маршруты обслуживает Minoan Lines?', 'Когда следующий рейс в Ираклион?', 'Какие варианты кают доступны?', 'Когда прибыть в порт?'] }, compliance: { title: 'Соответствие ЕС', refresh: 'Обновить', generateReport: 'Создать отчёт', generating: 'Создание...', totalCO2: 'Всего CO₂ (т)', etsAllowances: 'Квоты ETS', avgCII: 'Средний CII', reportDate: 'Дата отчёта', euEts: 'Отчёт EU ETS', fuelEu: 'FuelEU Maritime' }, helpdesk: { title: 'ИТ-служба поддержки', newTicket: 'Новый тикет', submit: 'Отправить (ИИ распределит)', titleLabel: 'Заголовок проблемы', descLabel: 'Опишите проблему', nameLabel: 'Ваше имя (необязательно)', noTickets: 'Тикетов нет. Создайте один!', markInProgress: 'В работе', markResolved: 'Решено', escalate: 'Эскалировать', aiSuggested: 'Ответ, предложенный ИИ', bookingRef: 'Номер брони', ticketNumber: 'Номер билета', filters: { all: 'Все', open: 'Открытые', in_progress: 'В работе', resolved: 'Решённые', escalated: 'Эскалированные' } }, analytics: { title: 'Анализ спроса', refresh: 'Обновить', weeklyPassengers: 'Пассажиры за неделю', weeklyRevenue: 'Выручка за неделю', peakRoute: 'Пиковый маршрут', forecastAccuracy: 'Точность прогноза', generateInsights: 'Создать инсайты для', forecastTitle: 'Прогноз на 7 дней', aiInsights: 'ИИ-инсайты спроса' }, common: { loading: 'Загрузка...', error: 'Произошла ошибка', retry: 'Повторить' } } },
  tr: { translation: { nav: { vessels: 'Gemi Ops', chat: 'AI Ajan', compliance: 'Uyumluluk', helpdesk: 'Destek', analytics: 'Analitik' }, home: { title: 'Minoan Lines AI Platformu', subtitle: 'AI Operasyon Platformu — Powered by IntegraMind AI × DeepSeek' }, vessels: { title: 'Gemi Operasyonları', refresh: 'Yenile', lastUpdated: 'Son güncelleme', speed: 'Hız', fuel: 'Yakıt', eta: 'TTV', delayRisk: 'Gecikme Riski', status: { underway: 'Seyirde', at_anchor: 'Demirlemiş', moored: 'Yanaşmış' } }, chat: { title: 'AI Müşteri Hizmetleri', placeholder: 'Mesajınızı yazın...', suggestions: ['Minoan Lines hangi güzergahları işletiyor?', 'Heraklion\'a sonraki sefer ne zaman?', 'Hangi kabin seçenekleri mevcut?', 'Limana ne zaman varmalıyım?'] }, compliance: { title: 'AB Uyumluluğu', refresh: 'Yenile', generateReport: 'Rapor Oluştur', generating: 'Oluşturuluyor...', totalCO2: 'Toplam CO₂ (ton)', etsAllowances: 'ETS İzinleri', avgCII: 'Ort. CII', reportDate: 'Rapor Tarihi', euEts: 'EU ETS Raporu', fuelEu: 'FuelEU Maritime' }, helpdesk: { title: 'BT Yardım Masası', newTicket: 'Yeni Bilet', submit: 'Gönder (AI sınıflandıracak)', titleLabel: 'Sorun başlığı', descLabel: 'Sorunu açıklayın', nameLabel: 'Adınız (isteğe bağlı)', noTickets: 'Bilet yok. Bir tane oluşturun!', markInProgress: 'İşlemde', markResolved: 'Çözüldü', escalate: 'Tırmandır', aiSuggested: 'AI Önerilen Yanıt', bookingRef: 'Rezervasyon Ref.', ticketNumber: 'Bilet No.', filters: { all: 'Tümü', open: 'Açık', in_progress: 'İşlemde', resolved: 'Çözüldü', escalated: 'Tırmanmış' } }, analytics: { title: 'Talep Analitiği', refresh: 'Yenile', weeklyPassengers: 'Haftalık Yolcular', weeklyRevenue: 'Haftalık Gelir', peakRoute: 'Zirve Güzergah', forecastAccuracy: 'Tahmin Doğruluğu', generateInsights: 'İçgörü Oluştur:', forecastTitle: '7 Günlük Talep Tahmini', aiInsights: 'AI Talep İçgörüleri' }, common: { loading: 'Yükleniyor...', error: 'Bir hata oluştu', retry: 'Tekrar Dene' } } },
  nl: { translation: { nav: { vessels: 'Scheepvaart', chat: 'AI-agent', compliance: 'Naleving', helpdesk: 'Helpdesk', analytics: 'Analyse' }, home: { title: 'Minoan Lines AI-platform', subtitle: 'AI-operatieplatform — Powered by IntegraMind AI × DeepSeek' }, vessels: { title: 'Scheepsoperaties', refresh: 'Vernieuwen', lastUpdated: 'Laatste update', speed: 'Snelheid', fuel: 'Brandstof', eta: 'ETA', delayRisk: 'Vertragingsrisico', status: { underway: 'Onderweg', at_anchor: 'Voor anker', moored: 'Afgemeerd' } }, chat: { title: 'AI Klantenservice', placeholder: 'Typ uw bericht...', suggestions: ['Welke routes heeft Minoan Lines?', 'Wanneer vertrekt de volgende boot naar Heraklion?', 'Welke cabine-opties zijn beschikbaar?', 'Wanneer moet ik in de haven zijn?'] }, compliance: { title: 'EU-naleving', refresh: 'Vernieuwen', generateReport: 'Rapport genereren', generating: 'Genereren...', totalCO2: 'Totaal CO₂ (ton)', etsAllowances: 'ETS-rechten', avgCII: 'Gem. CII', reportDate: 'Rapportdatum', euEts: 'EU ETS-rapport', fuelEu: 'FuelEU Maritime' }, helpdesk: { title: 'IT-helpdesk', newTicket: 'Nieuw ticket', submit: 'Indienen (AI triageert)', titleLabel: 'Probleemtitel', descLabel: 'Beschrijf het probleem', nameLabel: 'Uw naam (optioneel)', noTickets: 'Geen tickets gevonden. Maak er een!', markInProgress: 'In behandeling', markResolved: 'Opgelost', escalate: 'Escaleren', aiSuggested: 'AI-voorgesteld antwoord', bookingRef: 'Boekingsref.', ticketNumber: 'Ticket nr.', filters: { all: 'Alle', open: 'Open', in_progress: 'In behandeling', resolved: 'Opgelost', escalated: 'Geëscaleerd' } }, analytics: { title: 'Vraaganalyse', refresh: 'Vernieuwen', weeklyPassengers: 'Wekelijkse passagiers', weeklyRevenue: 'Wekelijkse omzet', peakRoute: 'TopRoute', forecastAccuracy: 'Voorspellingsnauwkeurigheid', generateInsights: 'Inzichten genereren voor', forecastTitle: '7-daagse vraagprognose', aiInsights: 'AI-vraaginzichten' }, common: { loading: 'Laden...', error: 'Er is een fout opgetreden', retry: 'Opnieuw proberen' } } },
  pl: { translation: { nav: { vessels: 'Operacje', chat: 'Agent AI', compliance: 'Zgodność', helpdesk: 'Wsparcie', analytics: 'Analityka' }, home: { title: 'Platforma AI Minoan Lines', subtitle: 'Platforma Operacyjna AI — Powered by IntegraMind AI × DeepSeek' }, vessels: { title: 'Operacje Statków', refresh: 'Odśwież', lastUpdated: 'Ostatnia aktualizacja', speed: 'Prędkość', fuel: 'Paliwo', eta: 'ETA', delayRisk: 'Ryzyko opóźnienia', status: { underway: 'W drodze', at_anchor: 'Na kotwicy', moored: 'Zacumowany' } }, chat: { title: 'Obsługa Klienta AI', placeholder: 'Wpisz wiadomość...', suggestions: ['Jakie trasy obsługuje Minoan Lines?', 'Kiedy następny rejs do Heraklion?', 'Jakie opcje kabin są dostępne?', 'Kiedy przybyć do portu?'] }, compliance: { title: 'Zgodność UE', refresh: 'Odśwież', generateReport: 'Generuj raport', generating: 'Generowanie...', totalCO2: 'Łączny CO₂ (tony)', etsAllowances: 'Uprawnienia ETS', avgCII: 'Śr. CII', reportDate: 'Data raportu', euEts: 'Raport EU ETS', fuelEu: 'FuelEU Maritime' }, helpdesk: { title: 'Helpdesk IT', newTicket: 'Nowy bilet', submit: 'Wyślij (AI sklasyfikuje)', titleLabel: 'Tytuł problemu', descLabel: 'Opisz problem', nameLabel: 'Twoje imię (opcjonalne)', noTickets: 'Brak biletów. Utwórz jeden!', markInProgress: 'W trakcie', markResolved: 'Rozwiązano', escalate: 'Eskaluj', aiSuggested: 'Odpowiedź sugerowana przez AI', bookingRef: 'Ref. rezerwacji', ticketNumber: 'Nr biletu', filters: { all: 'Wszystkie', open: 'Otwarte', in_progress: 'W trakcie', resolved: 'Rozwiązane', escalated: 'Eskalowane' } }, analytics: { title: 'Analityka popytu', refresh: 'Odśwież', weeklyPassengers: 'Tygodniowi pasażerowie', weeklyRevenue: 'Tygodniowe przychody', peakRoute: 'Szczytowa trasa', forecastAccuracy: 'Dokładność prognozy', generateInsights: 'Generuj wnioski dla', forecastTitle: 'Prognoza 7-dniowa', aiInsights: 'Wnioski AI dot. popytu' }, common: { loading: 'Ładowanie...', error: 'Wystąpił błąd', retry: 'Spróbuj ponownie' } } },
  sv: { translation: { nav: { vessels: 'Fartygsops', chat: 'AI-agent', compliance: 'Efterlevnad', helpdesk: 'Helpdesk', analytics: 'Analys' }, home: { title: 'Minoan Lines AI-plattform', subtitle: 'AI-driftsplattform — Powered by IntegraMind AI × DeepSeek' }, vessels: { title: 'Fartygsdrift', refresh: 'Uppdatera', lastUpdated: 'Senast uppdaterad', speed: 'Hastighet', fuel: 'Bränsle', eta: 'ETA', delayRisk: 'Förseningsrisk', status: { underway: 'Under gång', at_anchor: 'För ankar', moored: 'Förtöjd' } }, chat: { title: 'AI Kundtjänst', placeholder: 'Skriv ditt meddelande...', suggestions: ['Vilka rutter driver Minoan Lines?', 'När avgår nästa båt till Heraklion?', 'Vilka hyttalternativ finns?', 'När ska jag anlända till hamnen?'] }, compliance: { title: 'EU-efterlevnad', refresh: 'Uppdatera', generateReport: 'Generera rapport', generating: 'Genererar...', totalCO2: 'Total CO₂ (ton)', etsAllowances: 'ETS-tillstånd', avgCII: 'Medel-CII', reportDate: 'Rapportdatum', euEts: 'EU ETS-rapport', fuelEu: 'FuelEU Maritime' }, helpdesk: { title: 'IT-helpdesk', newTicket: 'Ny biljett', submit: 'Skicka (AI triagerar)', titleLabel: 'Problemtitel', descLabel: 'Beskriv problemet', nameLabel: 'Ditt namn (valfritt)', noTickets: 'Inga biljetter hittades. Skapa en!', markInProgress: 'Pågår', markResolved: 'Löst', escalate: 'Eskalera', aiSuggested: 'AI-föreslagen svar', bookingRef: 'Bokningsref.', ticketNumber: 'Biljettnr.', filters: { all: 'Alla', open: 'Öppna', in_progress: 'Pågår', resolved: 'Lösta', escalated: 'Eskalerade' } }, analytics: { title: 'Efterfrågeanalys', refresh: 'Uppdatera', weeklyPassengers: 'Veckovisa passagerare', weeklyRevenue: 'Veckovisa intäkter', peakRoute: 'Topprutt', forecastAccuracy: 'Prognosnoggrannhet', generateInsights: 'Generera insikter för', forecastTitle: '7-dagarsprognos', aiInsights: 'AI efterfrågeinsikter' }, common: { loading: 'Laddar...', error: 'Ett fel inträffade', retry: 'Försök igen' } } },
  ko: { translation: { nav: { vessels: '선박 운항', chat: 'AI 상담원', compliance: '컴플라이언스', helpdesk: '헬프데스크', analytics: '분석' }, home: { title: 'Minoan Lines AI 플랫폼', subtitle: 'AI 운영 플랫폼 — Powered by IntegraMind AI × DeepSeek' }, vessels: { title: '선박 운항', refresh: '새로고침', lastUpdated: '마지막 업데이트', speed: '속도', fuel: '연료', eta: '도착예정', delayRisk: '지연 위험', status: { underway: '항해 중', at_anchor: '닻 내림', moored: '정박' } }, chat: { title: 'AI 고객 서비스', placeholder: '메시지를 입력하세요...', suggestions: ['Minoan Lines는 어떤 노선을 운항하나요?', '헤라클리온행 다음 출발은 언제인가요?', '어떤 선실 옵션이 있나요?', '항구에 언제 도착해야 하나요?'] }, compliance: { title: 'EU 컴플라이언스', refresh: '새로고침', generateReport: '보고서 생성', generating: '생성 중...', totalCO2: '총 CO₂ (톤)', etsAllowances: 'ETS 허용량', avgCII: '평균 CII', reportDate: '보고서 날짜', euEts: 'EU ETS 보고서', fuelEu: 'FuelEU Maritime' }, helpdesk: { title: 'IT 헬프데스크', newTicket: '새 티켓', submit: '제출 (AI가 분류)', titleLabel: '문제 제목', descLabel: '문제 설명', nameLabel: '이름 (선택)', noTickets: '티켓이 없습니다. 하나 만드세요!', markInProgress: '진행 중', markResolved: '해결됨', escalate: '에스컬레이션', aiSuggested: 'AI 제안 답변', bookingRef: '예약 번호', ticketNumber: '티켓 번호', filters: { all: '전체', open: '열림', in_progress: '진행 중', resolved: '해결됨', escalated: '에스컬레이션' } }, analytics: { title: '수요 분석', refresh: '새로고침', weeklyPassengers: '주간 승객', weeklyRevenue: '주간 수익', peakRoute: '피크 노선', forecastAccuracy: '예측 정확도', generateInsights: '인사이트 생성:', forecastTitle: '7일 수요 예측', aiInsights: 'AI 수요 인사이트' }, common: { loading: '로딩 중...', error: '오류가 발생했습니다', retry: '다시 시도' } } },
  hi: { translation: { nav: { vessels: 'जहाज़ संचालन', chat: 'AI एजेंट', compliance: 'अनुपालन', helpdesk: 'हेल्पडेस्क', analytics: 'विश्लेषण' }, home: { title: 'Minoan Lines AI प्लेटफ़ॉर्म', subtitle: 'AI संचालन प्लेटफ़ॉर्म — Powered by IntegraMind AI × DeepSeek' }, vessels: { title: 'जहाज़ संचालन', refresh: 'ताज़ा करें', lastUpdated: 'अंतिम अपडेट', speed: 'गति', fuel: 'ईंधन', eta: 'ETA', delayRisk: 'विलंब जोखिम', status: { underway: 'यात्रा में', at_anchor: 'लंगर पर', moored: 'बंधा हुआ' } }, chat: { title: 'AI ग्राहक सेवा', placeholder: 'अपना संदेश टाइप करें...', suggestions: ['Minoan Lines कौन से मार्ग संचालित करती है?', 'Heraklion के लिए अगली रवानगी कब है?', 'कौन से केबिन विकल्प उपलब्ध हैं?', 'मुझे बंदरगाह पर कब पहुंचना चाहिए?'] }, compliance: { title: 'EU अनुपालन', refresh: 'ताज़ा करें', generateReport: 'रिपोर्ट बनाएं', generating: 'बना रहे हैं...', totalCO2: 'कुल CO₂ (टन)', etsAllowances: 'ETS अनुमतियाँ', avgCII: 'औसत CII', reportDate: 'रिपोर्ट तिथि', euEts: 'EU ETS रिपोर्ट', fuelEu: 'FuelEU Maritime' }, helpdesk: { title: 'IT हेल्पडेस्क', newTicket: 'नई टिकट', submit: 'भेजें (AI वर्गीकृत करेगा)', titleLabel: 'समस्या शीर्षक', descLabel: 'समस्या का वर्णन करें', nameLabel: 'आपका नाम (वैकल्पिक)', noTickets: 'कोई टिकट नहीं। एक बनाएं!', markInProgress: 'प्रगति में', markResolved: 'हल हुआ', escalate: 'एस्केलेट करें', aiSuggested: 'AI सुझाया गया जवाब', bookingRef: 'बुकिंग रेफ.', ticketNumber: 'टिकट नं.', filters: { all: 'सभी', open: 'खुला', in_progress: 'प्रगति में', resolved: 'हल', escalated: 'एस्केलेटेड' } }, analytics: { title: 'मांग विश्लेषण', refresh: 'ताज़ा करें', weeklyPassengers: 'साप्ताहिक यात्री', weeklyRevenue: 'साप्ताहिक राजस्व', peakRoute: 'पीक मार्ग', forecastAccuracy: 'पूर्वानुमान सटीकता', generateInsights: 'इनसाइट्स बनाएं:', forecastTitle: '7-दिन की मांग पूर्वानुमान', aiInsights: 'AI मांग इनसाइट्स' }, common: { loading: 'लोड हो रहा है...', error: 'एक त्रुटि हुई', retry: 'पुनः प्रयास करें' } } },
  uk: { translation: { nav: { vessels: 'Флот', chat: 'ІІ-агент', compliance: 'Відповідність', helpdesk: 'Підтримка', analytics: 'Аналітика' }, home: { title: 'ІІ-платформа Minoan Lines', subtitle: 'Операційна ІІ-платформа — Powered by IntegraMind AI × DeepSeek' }, vessels: { title: 'Операції флоту', refresh: 'Оновити', lastUpdated: 'Останнє оновлення', speed: 'Швидкість', fuel: 'Паливо', eta: 'ОЧП', delayRisk: 'Ризик затримки', status: { underway: 'В дорозі', at_anchor: 'На якорі', moored: 'Пришвартовано' } }, chat: { title: 'ІІ-служба підтримки', placeholder: 'Введіть повідомлення...', suggestions: ['Які маршрути обслуговує Minoan Lines?', 'Коли наступний рейс до Іракліона?', 'Які варіанти кают доступні?', 'Коли прибути до порту?'] }, compliance: { title: 'Відповідність ЄС', refresh: 'Оновити', generateReport: 'Створити звіт', generating: 'Створення...', totalCO2: 'Всього CO₂ (т)', etsAllowances: 'Квоти ETS', avgCII: 'Середній CII', reportDate: 'Дата звіту', euEts: 'Звіт EU ETS', fuelEu: 'FuelEU Maritime' }, helpdesk: { title: 'ІТ-служба підтримки', newTicket: 'Новий тікет', submit: 'Надіслати (ІІ розподілить)', titleLabel: 'Заголовок проблеми', descLabel: 'Опишіть проблему', nameLabel: "Ваше ім'я (необов'язково)", noTickets: 'Тікетів немає. Створіть один!', markInProgress: 'В роботі', markResolved: 'Вирішено', escalate: 'Ескалювати', aiSuggested: 'Відповідь, запропонована ІІ', bookingRef: 'Номер бронювання', ticketNumber: 'Номер квитка', filters: { all: 'Всі', open: 'Відкриті', in_progress: 'В роботі', resolved: 'Вирішені', escalated: 'Ескальовані' } }, analytics: { title: 'Аналіз попиту', refresh: 'Оновити', weeklyPassengers: 'Пасажири за тиждень', weeklyRevenue: 'Виручка за тиждень', peakRoute: 'Пік маршруту', forecastAccuracy: 'Точність прогнозу', generateInsights: 'Створити інсайти для', forecastTitle: 'Прогноз на 7 днів', aiInsights: 'ІІ-інсайти попиту' }, common: { loading: 'Завантаження...', error: 'Сталася помилка', retry: 'Повторити' } } },
  ro: { translation: { nav: { vessels: 'Nave', chat: 'Agent AI', compliance: 'Conformitate', helpdesk: 'Asistență', analytics: 'Analiză' }, home: { title: 'Platforma AI Minoan Lines', subtitle: 'Platformă Operațională AI — Powered by IntegraMind AI × DeepSeek' }, vessels: { title: 'Operațiuni Nave', refresh: 'Actualizare', lastUpdated: 'Ultima actualizare', speed: 'Viteză', fuel: 'Combustibil', eta: 'ETA', delayRisk: 'Risc Întârziere', status: { underway: 'În navigare', at_anchor: 'La ancoră', moored: 'Acostat' } }, chat: { title: 'Agent AI Clienți', placeholder: 'Scrieți mesajul...', suggestions: ['Ce rute operează Minoan Lines?', 'Când este următoarea plecare spre Heraklion?', 'Ce opțiuni de cabină există?', 'Când să ajung la port?'] }, compliance: { title: 'Conformitate UE', refresh: 'Actualizare', generateReport: 'Generare Raport', generating: 'Se generează...', totalCO2: 'Total CO₂ (tone)', etsAllowances: 'Permise ETS', avgCII: 'CII Mediu', reportDate: 'Data Raport', euEts: 'Raport EU ETS', fuelEu: 'FuelEU Maritime' }, helpdesk: { title: 'Helpdesk IT', newTicket: 'Bilet Nou', submit: 'Trimite (AI va clasifica)', titleLabel: 'Titlu problemă', descLabel: 'Descrieți problema', nameLabel: 'Numele dvs. (opțional)', noTickets: 'Fără bilete. Creați unul!', markInProgress: 'În curs', markResolved: 'Rezolvat', escalate: 'Escaladare', aiSuggested: 'Răspuns sugerat AI', bookingRef: 'Ref. rezervare', ticketNumber: 'Nr. bilet', filters: { all: 'Toate', open: 'Deschise', in_progress: 'În curs', resolved: 'Rezolvate', escalated: 'Escalate' } }, analytics: { title: 'Analiza Cererii', refresh: 'Actualizare', weeklyPassengers: 'Pasageri Săptămânali', weeklyRevenue: 'Venituri Săptămânale', peakRoute: 'Rută de Vârf', forecastAccuracy: 'Precizie Prognoză', generateInsights: 'Generare Perspective pentru', forecastTitle: 'Prognoză 7 Zile', aiInsights: 'Perspective AI Cerere' }, common: { loading: 'Se încarcă...', error: 'A apărut o eroare', retry: 'Reîncercați' } } },
  cs: { translation: { nav: { vessels: 'Lodě', chat: 'AI Agent', compliance: 'Soulad', helpdesk: 'Podpora', analytics: 'Analytika' }, home: { title: 'AI platforma Minoan Lines', subtitle: 'Provozní AI platforma — Powered by IntegraMind AI × DeepSeek' }, vessels: { title: 'Provoz lodí', refresh: 'Obnovit', lastUpdated: 'Poslední aktualizace', speed: 'Rychlost', fuel: 'Palivo', eta: 'ETA', delayRisk: 'Riziko zpoždění', status: { underway: 'Na cestě', at_anchor: 'Na kotvě', moored: 'Přistaven' } }, chat: { title: 'AI zákaznický servis', placeholder: 'Napište zprávu...', suggestions: ['Jaké trasy Minoan Lines provozuje?', 'Kdy jede příští loď do Heraklion?', 'Jaké kabiny jsou k dispozici?', 'Kdy mám přijet do přístavu?'] }, compliance: { title: 'Soulad s EU', refresh: 'Obnovit', generateReport: 'Generovat zprávu', generating: 'Generování...', totalCO2: 'Celkový CO₂ (t)', etsAllowances: 'Povolenky ETS', avgCII: 'Průměr CII', reportDate: 'Datum zprávy', euEts: 'Zpráva EU ETS', fuelEu: 'FuelEU Maritime' }, helpdesk: { title: 'IT Helpdesk', newTicket: 'Nový tiket', submit: 'Odeslat (AI roztřídí)', titleLabel: 'Název problému', descLabel: 'Popište problém', nameLabel: 'Vaše jméno (volitelné)', noTickets: 'Žádné tikety. Vytvořte jeden!', markInProgress: 'Probíhá', markResolved: 'Vyřešeno', escalate: 'Eskalovat', aiSuggested: 'Odpověď navržená AI', bookingRef: 'Ref. rezervace', ticketNumber: 'Č. tiketu', filters: { all: 'Vše', open: 'Otevřené', in_progress: 'Probíhá', resolved: 'Vyřešené', escalated: 'Eskalované' } }, analytics: { title: 'Analýza poptávky', refresh: 'Obnovit', weeklyPassengers: 'Týdenní cestující', weeklyRevenue: 'Týdenní příjmy', peakRoute: 'Hlavní trasa', forecastAccuracy: 'Přesnost prognózy', generateInsights: 'Generovat přehledy pro', forecastTitle: '7denní prognóza', aiInsights: 'AI přehledy poptávky' }, common: { loading: 'Načítání...', error: 'Došlo k chybě', retry: 'Zkusit znovu' } } },
};

if (!i18n.isInitialized) {
  i18n
    .use(LanguageDetector)
    .use(initReactI18next)
    .init({
      resources,
      fallbackLng: 'en',
      interpolation: { escapeValue: false },
      detection: {
        order: ['localStorage', 'navigator'],
        caches: ['localStorage'],
      },
    });
}

export default i18n;
