import { NextResponse } from 'next/server';
import { Resend } from 'resend';

export const runtime = 'nodejs';

export async function POST(req: Request) {
  try {
    const { to, report_type, content, vessel_data } = await req.json();

    if (!to || !content) {
      return NextResponse.json({ error: 'recipient email and content required' }, { status: 400 });
    }

    const apiKey = process.env.RESEND_API_KEY;
    if (!apiKey) {
      return NextResponse.json({ error: 'Email service not configured — add RESEND_API_KEY to Vercel env vars' }, { status: 503 });
    }

    const resend = new Resend(apiKey);
    const reportTitle = report_type === 'fuel_eu' ? 'FuelEU Maritime' : 'EU ETS';
    const date = new Date().toLocaleDateString('en-GB', { day: '2-digit', month: 'long', year: 'numeric' });

    const vesselRows = vessel_data?.map((v: { vessel: string; co2_emissions_tons: number; cii_score: number; fueleu_rating: string }) => `
      <tr style="border-bottom:1px solid #e5e7eb">
        <td style="padding:8px 12px;font-weight:500">${v.vessel}</td>
        <td style="padding:8px 12px;text-align:center">${v.co2_emissions_tons}</td>
        <td style="padding:8px 12px;text-align:center">${v.cii_score}</td>
        <td style="padding:8px 12px;text-align:center">
          <span style="background:${v.fueleu_rating === 'A' ? '#dcfce7' : v.fueleu_rating === 'B' ? '#dbeafe' : '#fef9c3'};
            padding:2px 8px;border-radius:9999px;font-size:12px;font-weight:600">${v.fueleu_rating}</span>
        </td>
      </tr>`).join('') || '';

    const html = `
<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width"></head>
<body style="font-family:Inter,system-ui,sans-serif;background:#f3f4f6;margin:0;padding:24px">
  <div style="max-width:680px;margin:0 auto;background:#fff;border-radius:12px;overflow:hidden;box-shadow:0 1px 3px rgba(0,0,0,.1)">
    <div style="background:#001A4D;padding:24px 32px">
      <div style="display:flex;align-items:center;gap:12px">
        <div style="font-size:24px">⚓</div>
        <div>
          <div style="color:#C9A84C;font-size:12px;font-weight:600;letter-spacing:.05em;text-transform:uppercase">Minoan Lines S.A.</div>
          <div style="color:#fff;font-size:18px;font-weight:700">${reportTitle} Compliance Report</div>
        </div>
      </div>
      <div style="color:#93c5fd;font-size:13px;margin-top:8px">${date} · Generated by IntegraMind AI × DeepSeek</div>
    </div>

    <div style="padding:24px 32px">
      <div style="background:#f0f9ff;border-left:4px solid #003087;padding:16px;border-radius:0 8px 8px 0;margin-bottom:24px">
        <div style="white-space:pre-wrap;font-size:14px;line-height:1.7;color:#1e3a5f">${content.replace(/</g, '&lt;').replace(/>/g, '&gt;')}</div>
      </div>

      ${vessel_data?.length ? `
      <h3 style="font-size:14px;font-weight:600;color:#111827;margin-bottom:12px">Fleet Data Summary</h3>
      <table style="width:100%;border-collapse:collapse;font-size:13px">
        <thead>
          <tr style="background:#f9fafb">
            <th style="padding:8px 12px;text-align:left;color:#6b7280;font-weight:500">Vessel</th>
            <th style="padding:8px 12px;text-align:center;color:#6b7280;font-weight:500">CO₂ (t)</th>
            <th style="padding:8px 12px;text-align:center;color:#6b7280;font-weight:500">CII Score</th>
            <th style="padding:8px 12px;text-align:center;color:#6b7280;font-weight:500">FuelEU</th>
          </tr>
        </thead>
        <tbody>${vesselRows}</tbody>
      </table>` : ''}
    </div>

    <div style="background:#f9fafb;padding:16px 32px;border-top:1px solid #e5e7eb">
      <p style="font-size:12px;color:#9ca3af;margin:0">
        This report was automatically generated by the Minoan Lines AI Platform.
        Powered by <strong>IntegraMind AI</strong> · <a href="https://integramindai.com" style="color:#003087">integramindai.com</a>
      </p>
    </div>
  </div>
</body>
</html>`;

    const { data, error } = await resend.emails.send({
      from: 'Minoan Lines AI <reports@integramindai.com>',
      to: [to],
      subject: `${reportTitle} Compliance Report — Minoan Lines S.A. (${date})`,
      html,
    });

    if (error) throw new Error(error.message);

    return NextResponse.json({ success: true, email_id: data?.id });
  } catch (e) {
    return NextResponse.json(
      { error: e instanceof Error ? e.message : 'Failed to send email' },
      { status: 500 }
    );
  }
}
