"""
Compliance report models for Module 3.
"""
import uuid

from sqlalchemy import Column, DateTime, Float, Index, Integer, Numeric, String, Text, func
from sqlalchemy.dialects.postgresql import UUID

from database import Base


class ComplianceReport(Base):
    __tablename__ = "compliance_reports"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    report_type = Column(String(50), nullable=False)   # eu_ets | fueleu | iso9001 | athex_quarterly
    report_period = Column(String(30))                  # e.g. "2025-Q1" or "2025-03"
    vessel_name = Column(String(100))                   # null = fleet-wide

    # ETS / FuelEU figures
    fuel_consumed_mt = Column(Float)
    co2_emissions_mt = Column(Float)
    ets_allowances_required = Column(Float)
    ets_cost_eur = Column(Numeric(14, 2))
    ghg_intensity_gco2eq_mj = Column(Float)             # FuelEU GHG intensity
    fueleu_compliance_balance = Column(Float)

    # Report artifacts
    pdf_path = Column(String(500))
    json_data = Column(Text)                            # full report payload as JSON
    generated_by = Column(String(100), default="IntegraMind AI")

    # Delivery
    emailed_to = Column(String(500))
    emailed_at = Column(DateTime(timezone=True))
    status = Column(String(30), default="generated")   # generated | delivered | error

    disclaimer = Column(
        Text,
        default=(
            "Generated by IntegraMind AI for Minoan Lines S.A. — "
            "verify against official regulatory filings."
        ),
    )

    created_at = Column(DateTime(timezone=True), server_default=func.now())

    __table_args__ = (
        Index("ix_compliance_reports_type", "report_type"),
        Index("ix_compliance_reports_period", "report_period"),
        Index("ix_compliance_reports_vessel", "vessel_name"),
    )

    def __repr__(self) -> str:
        return f"<ComplianceReport {self.report_type} {self.report_period}>"


class FuelConsumptionRecord(Base):
    """Raw SCADA fuel data ingested per voyage leg."""
    __tablename__ = "fuel_consumption_records"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    vessel_name = Column(String(100), nullable=False)
    voyage_id = Column(String(100))
    route = Column(String(200))

    departure_port = Column(String(100))
    arrival_port = Column(String(100))
    departure_time = Column(DateTime(timezone=True))
    arrival_time = Column(DateTime(timezone=True))

    distance_nm = Column(Float)                         # nautical miles
    fuel_type = Column(String(50), default="HFO")       # HFO | MGO | LNG | biofuel
    fuel_consumed_mt = Column(Float)                    # metric tonnes
    co2_emission_factor = Column(Float, default=3.206)  # tCO2/tFuel for HFO
    co2_emissions_mt = Column(Float)

    is_eu_ets_voyage = Column(Integer, default=1)       # voyages between EU ports
    source = Column(String(50), default="scada_mock")

    created_at = Column(DateTime(timezone=True), server_default=func.now())
    idempotency_key = Column(String(200), unique=True)  # safe to retry

    __table_args__ = (
        Index("ix_fuel_vessel_departure", "vessel_name", "departure_time"),
    )
